name: Deploy Website

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Deploying to surge
    steps:
      - uses: actions/checkout@v1
      - name: Install surge and fire deployment
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm install -g surge
      - run: npm install
      - run: npm run generate
      - run: surge ./dist/ OWAIS_PORTFOLIO_MYFARM.surge.sh --token ${{ secrets.SURGE_TOKEN }}
